# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/competition_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CompetitionDialog(object):
    def setupUi(self, CompetitionDialog):
        CompetitionDialog.setObjectName("CompetitionDialog")
        CompetitionDialog.resize(400, 300)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(CompetitionDialog)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setHorizontalSpacing(6)
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(CompetitionDialog)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameEdit = QtWidgets.QLineEdit(CompetitionDialog)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameEdit)
        self.surnameLabel = QtWidgets.QLabel(CompetitionDialog)
        self.surnameLabel.setObjectName("surnameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.surnameLabel)
        self.cityEdit = QtWidgets.QLineEdit(CompetitionDialog)
        self.cityEdit.setObjectName("cityEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cityEdit)
        self.genderLabel = QtWidgets.QLabel(CompetitionDialog)
        self.genderLabel.setObjectName("genderLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.genderLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.categoryComboBox = QtWidgets.QComboBox(CompetitionDialog)
        self.categoryComboBox.setObjectName("categoryComboBox")
        self.horizontalLayout.addWidget(self.categoryComboBox)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dateEdit = QtWidgets.QDateEdit(CompetitionDialog)
        self.dateEdit.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_3.addWidget(self.dateEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.dataLabel = QtWidgets.QLabel(CompetitionDialog)
        self.dataLabel.setObjectName("dataLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.dataLabel)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(CompetitionDialog)
        self.buttonBox.setToolTip("")
        self.buttonBox.setStatusTip("")
        self.buttonBox.setWhatsThis("")
        self.buttonBox.setAccessibleName("")
        self.buttonBox.setAccessibleDescription("")
        self.buttonBox.setStyleSheet("")
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)

        self.retranslateUi(CompetitionDialog)
        QtCore.QMetaObject.connectSlotsByName(CompetitionDialog)

    def retranslateUi(self, CompetitionDialog):
        _translate = QtCore.QCoreApplication.translate
        CompetitionDialog.setWindowTitle(_translate("CompetitionDialog", "Новое соревнование"))
        self.nameLabel.setText(_translate("CompetitionDialog", "Название"))
        self.nameEdit.setPlaceholderText(_translate("CompetitionDialog", "Введите название"))
        self.surnameLabel.setText(_translate("CompetitionDialog", "Город"))
        self.cityEdit.setPlaceholderText(_translate("CompetitionDialog", "Введите город"))
        self.genderLabel.setText(_translate("CompetitionDialog", "Категория"))
        self.dataLabel.setText(_translate("CompetitionDialog", "Дата"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CompetitionDialog = QtWidgets.QDialog()
    ui = Ui_CompetitionDialog()
    ui.setupUi(CompetitionDialog)
    CompetitionDialog.show()
    sys.exit(app.exec_())
